### ISSUE TITLE
Build fails after QWIRE version update

### ISSUE THREAD

**Issue by k4rtik** [inQWIRE/SQIRE#1]
```bash
$ coqc --version
The Coq Proof Assistant, version 8.9.1 (August 2019)
compiled on Aug 25 2019 21:25:38 with OCaml 4.07.1
$ make
COQC lib/QWIRE/Complex.v
File "./lib/QWIRE/Complex.v", line 38, characters 8-13:
Error:
Syntax error: 'Equivalent' 'Keys' expected after 'Declare' (in [vernac:command]).

make[1]: *** [lib/QWIRE/Complex.vo] Error 1
make: *** [all] Error 2
```

I tried building QWIRE on the master branch and got the same error:
```bash
$ make
coq_makefile -f _CoqProject -o CoqMakefile
/Library/Developer/CommandLineTools/usr/bin/make --no-print-directory -f CoqMakefile
COQC Complex.v
File "./Complex.v", line 38, characters 8-13:
Error:
Syntax error: 'Equivalent' 'Keys' expected after 'Declare' (in [vernac:command]).

make[2]: *** [Complex.vo] Error 1
make[1]: *** [all] Error 2
make: *** [invoke-coqmakefile] Error 2
```

**Comment by rnrand** [comment]
Should be fixed, but since it's a compatibility issue (8.9 doesn't allow you to declare scopes), want to confirm that it's fixed on your machine?

I'd also report QWIRE issues on the QWIRE repo.

**Comment by k4rtik** [comment]
QWIRE builds now. Are you all using Coq 8.10 beta?

Because I ran into another issue in the SQIRE build because of this change: https://github.com/inQWIRE/SQIRE/commit/3244281eb0c16b7bc812929416732009490b1849#diff-385bec7ec6ffbe40ba252165c7b7db75L834-R834

```
$ make
COQC mapper/MappingExamples.v
     = [2; 3; 4; 5]
     : list nat
[...]
     = uapp2 U_CNOT 2 1
     : base_ucom (test_nr * test_nc)
     = (((((uapp2 U_CNOT 0 1; uapp2 U_CNOT 1 0); uapp2 U_CNOT 0 1);
          ((((uapp2 U_CNOT 1 2; uapp2 U_CNOT 2 1); uapp2 U_CNOT 1 2);
            uapp2 U_CNOT 2 3);
           ((uapp2 U_CNOT 1 2; uapp2 U_CNOT 2 1); uapp2 U_CNOT 1 2)));
         ((uapp2 U_CNOT 0 1; uapp2 U_CNOT 1 0); uapp2 U_CNOT 0 1));
        ((((uapp2 U_CNOT 4 3; uapp2 U_CNOT 3 4); uapp2 U_CNOT 4 3);
          uapp2 U_CNOT 3 8);
         ((uapp2 U_CNOT 4 3; uapp2 U_CNOT 3 4); uapp2 U_CNOT 4 3)));
       ((((uapp2 U_CNOT 12 7; uapp2 U_CNOT 7 12); uapp2 U_CNOT 12 7);
         uapp2 U_CNOT 7 6);
        ((uapp2 U_CNOT 12 7; uapp2 U_CNOT 7 12); uapp2 U_CNOT 12 7))
     : base_ucom (test_nr * test_nc)
File "./mapper/MappingExamples.v", line 834, characters 42-43:
Error: This proof is focused, but cannot be unfocused this way

make[1]: *** [mapper/MappingExamples.vo] Error 1
make: *** [all] Error 2
```

**Comment by khieta** [comment]
Hi Kartik, I'll be working on fixing this today. I'll keep you posted.

**Comment by k4rtik** [comment]
Sure, thanks. I mean if it helps, I can just use the 8.10 beta too. Proofs seem to become simpler from Robert's changes for 8.10.

**Comment by khieta** [comment]
I'm also using v8.9.1, so I'd like to make sure everything compiles for that version.

**Comment by khieta** [comment]
This should be fixed with my latest push. Let me know if it compiles for you (directed at both Robert & Kartik). I'll be away from my computer for a bit, but I can respond to issues later tonight.

Note that we now use a Makefile like QWIRE's, so you can use 'make all' to compile everything.

**Comment by k4rtik** [comment]
Thanks!

It worked fine on my Linux box with 8.9. I will wait for @rnrand to close the issue if it works on 8.10 too.
